name: App & Mongo Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
        - name: log node version
          run: node -v
        - name: step with docker
          uses: docker://node:12.12.1-alpine3.10
          with:
            entrypoint: /bin/echo
            args: 'Hello World'
  node-docker:
    runs-on: ubuntu-latest
    services:
      # like a docker compose
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports: 
          - 27017:27017
    # container: 
    #   image: node:13.5.0-alpine3.10
      # env:
      # ports:
      # volumes:
      # options:
    steps:
      # - name: Log node version
      #   run: |
      #     node -v
      #     cat /etc/os-release
      - name: create a user
        run: |
          payload='
            {
              "username": "user-1",
              "address": "address-1"
            }
            '
          echo $payload | curl \
            -H "Content-Type: application/json" \
            -X POST \
            http://localhost:3001/api/user \
            -d @- \
            -v
      - name: Get Users
        run: |
          curl http://localhost:3001/api/users
              