
name: Matrix
on: push

jobs:
  node-version: 
    runs-on: ubuntu-latest
    steps:
        - name: Log node version
          run: node -v
        - name: setup node version 6
          uses: actions/setup-node@v1
          with:
            node-version: 10  
        - name: Log node version
          run: node -v
    
###
# The End.    