name: Shell Commands

on: [push, pull_request]

jobs:
    run-shell-command:
      runs-on: ubuntu-18.04
      steps:
          - name: echo a string
            run: echco "hello world"
          - name: multiline script
            run: |
              node -v
              npm -v